spring:
  profiles:
    # this sequence is master
    include: common-dev,uid-dev,common
  datasource:
    username: ENC(3+5Pg+H9L0s1ATmg/xTWLbNt9OeMFguochuRyTl9a4BGbD4lL2SLM8351rdHYhC2)
    password: ENC(MkGdNTchUL+OnF+nvm5YSSjWc7XeHLNab+KV9Wr3fqF1fAbEVLB2urZotLn8nAk1)
    url: ENC(ODg2HaThw6347pLMI7UzSCRU/FzNUPuITeCgAGQMpIzvnDc6pN7X4wc8G3K6i9c4iFy6LvNTfnZgnZGYa3bA3za4tc3nbvj/dIf3yofN/5mMQPYAwRv8bp92Y0c8MGW1rOsxQyUv9YwGc4tNcWWfylJFj3GxOXtp1LTNpMmw2VkVBnBlsk47zvk3qqtHPJJJ5JnFD/Pf32XRdTzXc3aOgDkqrQ9e+UALplaXoV4x+PQ8g3vusKOfbayCuaerFL/orG6MG22UWf1MlFUu6vM1NhY81n5RMK6P7c7VWN+SECxWnhqDtpu+74/gEfs1D9EeMh9t19L5bULFKcKstdKdJRUus6Rvk3KA+LFTwAz08K1iCQXpRzvv6poZhy2UCFb9eVZqMpFJ3NjfrpjA7HmI69WyEoR4Uj7HG4JgeX9WsxjE8G0CHHMVPQJR3TvQF17x)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20


