opentracing:
  jaeger:
    enabled: true
    enable-b3-propagation: true
    log-spans: false

common:
  logs:
    request-id:
      enabled: true
      key: X-B3-SpanId
    sls:
      enabled: false
      endpoint: cn-shanghai.log.aliyuncs.com
      access-key-id: ${SLS_ACCESS_ID}
      access-key-secret: ${SLS_ACCESS_SECRET}
      project: tims-cms-service-local
      log-store: tims-cms-service-local-logstore
      topic: ${spring.application.name}
      level: INFO
    logstash:
      enable: true
      host: frps.xxx.top
      port: 50000
