spring:
  profiles:
    # this sequence is master
    include: common-dev,database-dev,uid-dev,common
  redis:
    host: ENC(nqt57Pt5vouq7RVAl03akf/zwmO4nZYW3936v9nnTF9KkEDgMpjs5eEbv7HGW4dl)
    password: ENC(JIczcGuavcI1nX9NbM0YcDyHiQ834QTPhqmczAw+Qr8Nm6wPeq5p5M076HzPSbFF)
    port: ENC(AcXQfYO9iFqD0RYGjek03cmHP3k9y7fl9HEy41cg/mr0xoT4ApjXUbtlpKNK8OCp)
    database: 15
    enable: true
    redisson: classpath:redisson-dev.yml
#  cache:
#    # fix error: Cannot find cache named 'xx' for Builder Or Config Redis as cache management
#    type: simple

common:
  core:
    redis:
      module: common
      # expire-time: 24

zk:
  url: ENC(H/C9p7xqZLZYlBUKynSGsbRaYwnVIF3u9oCR0JE8zVrc9wPSV5WuK4MjEjh+FzAY+35kOiridZemdqK/yYpDug==)
  timeout: 1000
  retry: 3
