spring:
  profiles:
    active: dev
  application:
    name: custom-security-https
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    async:
      request-timeout: 20
    throw-exception-if-no-handler-found: true
  config:
    use-legacy-processing: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    default-property-inclusion: non_null
  web:
    resources:
      add-mappings: false
