name: Sonar CI

on:
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]


jobs:
  build-and-analyze:
    name: Sonar Analysis on JDK 8
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone for improving relevancy of SonarQube reporting
        fetch-depth: 1

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'zulu'
        cache: 'maven'

    # Cache Sonar packages which as used to run anaylysis and collect metrics
    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Run SonarQube Analysis
      run: mvn -B clean verify -DskipTests=true org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Alice52_${{ github.repository }} -Dsonar.organization=alice52
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # - name: Run SonarQube Analysis
    #   uses: sonarsource/sonarcloud-github-action@master
    #   with:
    #     projectBaseDir: .
    #     args: >
    #       -Dsonar.verbose=true
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

